// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TimeMsg.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _TIMEMSG_H_
#define _TIMEMSG_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TimeMsg_SOURCE)
#define TimeMsg_DllAPI __declspec( dllexport )
#else
#define TimeMsg_DllAPI __declspec( dllimport )
#endif // TimeMsg_SOURCE
#else
#define TimeMsg_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TimeMsg_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure TimeMsg defined by the user in the IDL file.
 * @ingroup TIMEMSG
 */
class TimeMsg
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TimeMsg();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TimeMsg();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object TimeMsg that will be copied.
     */
    eProsima_user_DllExport TimeMsg(
            const TimeMsg& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object TimeMsg that will be copied.
     */
    eProsima_user_DllExport TimeMsg(
            TimeMsg&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object TimeMsg that will be copied.
     */
    eProsima_user_DllExport TimeMsg& operator =(
            const TimeMsg& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object TimeMsg that will be copied.
     */
    eProsima_user_DllExport TimeMsg& operator =(
            TimeMsg&& x);

    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message);

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message);

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const;

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message();
    /*!
     * @brief This function sets a value in member index
     * @param _index New value for member index
     */
    eProsima_user_DllExport void index(
            uint32_t _index);

    /*!
     * @brief This function returns the value of member index
     * @return Value of member index
     */
    eProsima_user_DllExport uint32_t index() const;

    /*!
     * @brief This function returns a reference to member index
     * @return Reference to member index
     */
    eProsima_user_DllExport uint32_t& index();

    /*!
     * @brief This function sets a value in member hour
     * @param _hour New value for member hour
     */
    eProsima_user_DllExport void hour(
            uint32_t _hour);

    /*!
     * @brief This function returns the value of member hour
     * @return Value of member hour
     */
    eProsima_user_DllExport uint32_t hour() const;

    /*!
     * @brief This function returns a reference to member hour
     * @return Reference to member hour
     */
    eProsima_user_DllExport uint32_t& hour();

    /*!
     * @brief This function sets a value in member minute
     * @param _minute New value for member minute
     */
    eProsima_user_DllExport void minute(
            uint32_t _minute);

    /*!
     * @brief This function returns the value of member minute
     * @return Value of member minute
     */
    eProsima_user_DllExport uint32_t minute() const;

    /*!
     * @brief This function returns a reference to member minute
     * @return Reference to member minute
     */
    eProsima_user_DllExport uint32_t& minute();

    /*!
     * @brief This function sets a value in member second
     * @param _second New value for member second
     */
    eProsima_user_DllExport void second(
            uint32_t _second);

    /*!
     * @brief This function returns the value of member second
     * @return Value of member second
     */
    eProsima_user_DllExport uint32_t second() const;

    /*!
     * @brief This function returns a reference to member second
     * @return Reference to member second
     */
    eProsima_user_DllExport uint32_t& second();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const TimeMsg& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    std::string m_message;
    uint32_t m_index;
    uint32_t m_hour;
    uint32_t m_minute;
    uint32_t m_second;
};

#endif // _TIMEMSG_H_